/** @file
* @brief Data_structure of token used and returned by lexer
* @author Coder : pierrick.made
* @author Tester : pierrick.made & zakaria.ben-allal
* @author Reviewer : cloe.lacombe
*/

#pragma once

#include "../input_output/get_next_line.h"
#include "../data_structures/queue.h"

/** @enum token_lexer_type
* @brief Possible types of a token generated by the lexer
*/
enum token_lexer_type
{
    TOKEN_END_OF_INSTRUCTION = 1, /**< @brief end of an instruction ";" */
    TOKEN_EOF, /**< @brief end of file "\n" */
    TOKEN_OPERATOR, /**< @brief operators defined in scl (&&, ||, ;;, ...) */
    TOKEN_KEYWORD, /**< @brief reserved words like fi, then, ... */
    TOKEN_OTHER, /**< @brief any words without delimiters */
    TOKEN_ASSIGNEMENT, /**< @brief variable assignement */
    TOKEN_IO_NUMBER /**< @brief io number for redirections */
};

/** @struct token_lexer
* @brief Define a token generated by the lexer
*/
struct token_lexer
{
    char *data; /**< @brief token content (char*) */
    enum token_lexer_type type; /**< @brief type of the token */
};

/**
* @brief Add all token_lexer found in line to token_queue
* @param line The line to be divided into tokens by the lexer
* @param token_queue current token queue to fill with line's tokens
* @return success : token_queue, fail : NULL
* @relates token_lexer
*/
struct queue *lexer(char *line, struct queue *token_queue);

/**
* @brief return head of the lexer
* @param token_queue current token queue to fill with line's tokens
* @relates token_lexer
*/
struct token_lexer *token_lexer_head(struct queue *token_queue);

/**
* @brief pop head of the lexer
* @param token_queue current token queue to fill with line's tokens
* @relates token_lexer
*/
struct token_lexer *token_lexer_pop(struct queue *token_queue);

/**
* @brief Free the token struct and contained string (set token to NULL)
* @param token the token you want to free
* @relates token_lexer
*/
void token_lexer_free(struct token_lexer **token);

/**
* @brief Free the queue struct and all its tokens
* @param token_queue the queue you want to free
* @relates token_lexer
*/
void token_queue_free(struct queue **token_queue);

/**
* @brief Free all the tokens of the queue without freeing the queue
* @param token_queue the queue you want to free
* @relates token_lexer
*/
void token_queue_empty(struct queue *token_queue);

/**
* @brief get next next token
* @param token_queue the queue
* @relates token_lexer
*/
struct token_lexer *lexer_next_next(struct queue *token_queue);

/**
* @brief skip quoting (single and double quotes + backslash)
* @param cursor current pointer on a quoting character
* @param start_of_token other pointer on line which can change
*/
void skip_quoting(char **cursor, char **start_of_token);

/**
* @brief performs strpbrk but put at the end of line if strpbrk returns NULL
* @param line the line
* @param delimiters the delimiters
*/
char *get_delimiter(char *line, char *delimiters);

/**
* @brief find the corresponding closing braces
* @param cursor cursor to move
* @param token_stat the start of the line
*/
char *find_corresponding_parenthesis(char **cursor, char **token_start);